### PR TITLE
Adaptation for idxml support

### PR DESCRIPTION
**Pull request by Leon-Bichmann**
Hi @grosenberger ,

I just wanted to show you the main changes I did so far, in order to integrate idXML files.

- I guess it is quite error prone in this state, as it would only work with comet/percolator analyzed idXMLs.

 - Moreover, I had to "out-comment" the steps in the peptide/protein fdr calculation in library.py in order to get it run through. I was planing to input already processed idXMLs that were previously filtered based on peptide_fdr and don't contain decoy hits anymore.

Do you think if we would add another flag in the main / and or description this could be integrated in your master?

### CODE REVIEW

**Comment by grosenberger** [comment]
Hi @Leon-Bichmann 
Looks great! I think the solution with disabling FDR control as flag makes a lot of sense and will provide more flexibility with the support of additional formats in the future. Please let me know when you think that the patch is ready, then I will go ahead and merge.

**Comment by Leon-Bichmann** [comment]
Ok, perfect. I just tested it once more and from my side it is working fine. 

So if you are fine with the changes you can merge the PR now.

**Comment by Leon-Bichmann** [comment]
hmm.. one problem still seems to come when using the OpenSwathAssay generator afterwards.

it is storing the entries as b'strings now:
`b'sp|Q9BUL8|PDC10_HUMAN'        -       b'HQKKEFVKY'`

**Comment by Leon-Bichmann** [comment]
ok now its working fine

**Comment by grosenberger** [comment]
Fantastic, thanks for the PR!

**Pull request merged**
