### PR TITLE
Fix idxml parsing

### PR DESCRIPTION
**Pull request by jonasscheid**
Related to #112

@fcyu are you up for supporting this again? :) I would definitely keep an eye on the idxml-part of this repo if you would.

Tested with idXML `easypqp convert` and `easypqp library` locally worked fine.

### CODE REVIEW

**Comment by fcyu** [comment]
We are changing EasyPQP actively (I just merged 15 commits from the fork https://github.com/Nesvilab/easypqp ). I am not sure if your changes will break it. Also, I don't think idXML is commonly used. Thus, unfortunately, due to the limited bandwidth, I am not able review or merge this pull request. But I will keep it open in case others want to review and merge it.

Best,

Fengchao

**Comment by grosenberger** [comment]
I think this looks great and the changes seem to be entirely outside of the functions that FragPipe makes use of. And especially if idXML support is broken now (I never used it), it would be better to have it fixed. Since there seems to be no conflict, I will merge. @jonasscheid Would be great if you could monitor any changes to idXML in the future.

**Review by grosenberger — APPROVED** [review]

**Comment by jonasscheid** [comment]
Great! Sure will do, just ping me

**Comment by jonasscheid** [comment]
@grosenberger @fcyu will there be a minor release in the new future? I'd like to use it soon on a bigger scale

**Comment by fcyu** [comment]
Sure. I will release it today if George is too busy to do.

Best,

Fengchao

**Comment by fcyu** [comment]
Done https://github.com/grosenberger/easypqp/releases/tag/0.1.50

Best,

Fengchao

**Comment by jonasscheid** [comment]
Thanks you! 🙏🏼

**Pull request merged**
